In [1]:
### In this  Implementation , we will be creating Our own Dataset and then we will be creating a Model on that Dataset .

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline


In [2]:
from sklearn.datasets import make_classification  # It is having its own Dataset. By this we can create our own Dataset.
# The Benefit of doing this is :- This Dataset is Already Standardized , we don't have to do Standardiztion  and Normalization on this Dataset 
# We can directly  use this Dataset for Training our Model , we can Direclty Focus on Implementaion Part 

In [3]:
## Let's Create the Dataset
X ,Y = make_classification(n_samples=1000 ,n_features=10 , n_classes=2 ,random_state= 42)
 # Here You are seeing this X and Y , this are My Independent and Dependent Features Respectively..
 # n_samples=1000 :- Means I am Creating 1000 rows
 # n_features=10 :- Means I am creating 10 columns 
 # n_Classes =2 :- I am Creating 2 Classes 
  # randome State :- It is the Seed Value so  that we can get the same value as we run the code Everytime
    


In [4]:
pd.DataFrame(X) # This is My Independent Features 
pd.DataFrame(Y) # This is my Dependent Features 
# Like that Here , we have Succesfully Created our Own Dataset, also we have Succesfully Craeted Dependent / Independent Features 

0
0    0
1    1
2    1
3    0
4    1
..  ..
995  1
996  1
997  0
998  0
999  0

[1000 rows x 1 columns]

In [5]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0    0.964799 -0.066449  0.986768 -0.358079  0.997266  1.181890 -1.615679   
1   -0.916511 -0.566395 -1.008614  0.831617 -1.176962  1.820544  1.752375   
2   -0.109484 -0.432774 -0.457649  0.793818 -0.268646 -1.836360  1.239086   
3    1.750412  2.023606  1.688159  0.006800 -1.607661  0.184741 -2.619427   
4   -0.224726 -0.711303 -0.220778  0.117124  1.536061  0.597538  0.348645   
..        ...       ...       ...       ...       ...       ...       ...   
995 -1.367638  1.462255 -1.154918 -0.290454 -0.413424  0.032396  1.545490   
996 -1.514876 -3.221016 -1.300744  0.395599 -0.527994  1.353069  1.777506   
997  1.674633  1.754933  1.586154  0.018402 -1.514470  0.321593 -2.417694   
998 -0.778609 -0.835689 -0.194842  1.097220  0.180071 -0.272933 -0.533188   
999  0.248454 -1.003439  0.360460 -0.331352  1.389764 -1.345210 -0.740875   

            7         8         9  
0   -1.210161 -0.628077  1.227274  
1   -0.984534  0.363896  0.209470  
2   -0.246383 -1.058145 -0.297376  
3   -0.357445 -1.473127 -0.190039  
4   -0.939156  0.175915  0.236224  
..        ...       ...       ...  
995  1.428760  1.687092  1.072542  
996 -1.680870  1.798510  0.034272  
997  0.692723 -1.503850  0.225264  
998 -0.497354  2.472138  0.867187  
999  0.773240  0.185734  1.416412  

[1000 rows x 10 columns]

In [6]:
Y

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,

In [7]:
### Now , Let's Split the Dataset into "Train-Test"
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test= train_test_split(X,Y ,test_size=0.25 ,random_state=42)


In [8]:
#Model Training 
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression() # Here Inside this There is one Parameter Called as "Calss_weight -" is Imp in Imbalaced Dataset , It will tell you to Focus on which  Dataset or Data  


In [9]:
logistic.fit(X_train,Y_train) # Model Training 
Y_pred=logistic.predict(X_test)
print(Y_pred)

[0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 1 1 1 1 0 1 0 0 1 0 0 1 1 1 1 0 0 0 0 1
 1 1 1 0 1 1 0 0 0 1 1 1 1 0 1 1 0 1 0 1 0 1 0 1 0 0 1 1 1 0 0 1 1 1 1 1 0
 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 1 1 1 1 1 1 0 0 1 0 1 0 1 0 0 1 0 1 1 1 1
 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 0 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 1 0 0 1 1 1 1 1 1 1
 0 0 0 0 1 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 1 0 1 0 1 1 0
 0 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1 0 1 0]


In [14]:
logistic.predict_proba(X_test) # It will give you the Probability of the Prediction 


array([[7.80402833e-01, 2.19597167e-01],
       [3.33949444e-02, 9.66605056e-01],
       [6.54296825e-01, 3.45703175e-01],
       [7.74596952e-02, 9.22540305e-01],
       [9.74932212e-01, 2.50677881e-02],
       [4.02885463e-02, 9.59711454e-01],
       [9.77941181e-01, 2.20588194e-02],
       [9.53536485e-01, 4.64635153e-02],
       [7.96205025e-01, 2.03794975e-01],
       [6.82676128e-01, 3.17323872e-01],
       [9.11092679e-01, 8.89073209e-02],
       [2.49227688e-01, 7.50772312e-01],
       [5.20867594e-01, 4.79132406e-01],
       [2.11303097e-01, 7.88696903e-01],
       [7.85887817e-01, 2.14112183e-01],
       [9.43614105e-01, 5.63858947e-02],
       [2.64777377e-02, 9.73522262e-01],
       [3.45014892e-01, 6.54985108e-01],
       [3.19886760e-01, 6.80113240e-01],
       [2.00611174e-01, 7.99388826e-01],
       [4.95911186e-01, 5.04088814e-01],
       [9.62345871e-01, 3.76541287e-02],
       [1.92455811e-01, 8.07544189e-01],
       [7.86728233e-01, 2.13271767e-01],
       [8.671754

In [15]:
logistic.score(X_test,Y_test) # It will give you the Accuracy of the Model


0.84

In [ ]:
# Let's Check the Accuarcy using Performance Matrix 
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
score =accuracy_score(Y_test,Y_pred)
print(score)
cm= confusion_matrix(Y_test,Y_pred)
print(cm)

print(classification_report(Y_test,Y_pred))

## Here Accuracy I'm getting is 84%...

0.84
[[ 98  15]
 [ 25 112]]
              precision    recall  f1-score   support

           0       0.80      0.87      0.83       113
           1       0.88      0.82      0.85       137

    accuracy                           0.84       250
   macro avg       0.84      0.84      0.84       250
weighted avg       0.84      0.84      0.84       250



In [20]:
  # What is Hyper -paramter tunning ? Why we do this ?
 # --> Hyper-Parameter Tunning is the Process of Choosing the Optimal Parameter for the Model , so that we can get the Best Model
# We can do this becoz , we can get the Best Model and we can Get the Best Accuracy of the Model 

### HYPER-PARAMTER TUNNING AND CROSS VALIDATION

In [11]:
model =LogisticRegression() # 
penalty =["l1","l2","elasticnet"] # It is the Regularization Parameter , It is used to avoid Over -fitting 
C_values=[100,10,1.0,0.1,0.01] # C_Values it is also --//-- 
solver=["newton-cg","lbfgs","liblinear","sag", "saga"] # It is the Optimization Algorithm , which is used to find the Optimal Parameter


In [14]:
params=dict(penalty=penalty, C=C_values,solver=solver) # It is the Dictionary , which is having the Key and Value Pair 
params

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1.0, 0.1, 0.01],
 'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']}

In [16]:
###Grid Search CV 
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
Cv=StratifiedKFold()
grid = GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=Cv,n_jobs=-1)

In [17]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [19]:
grid.fit(X_train,Y_train)
grid.best_params_

d:\PYTHONCODE\venv\lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
200 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "d:\PYTHONCODE\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\PYTHONCODE\venv\lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "d:\PYTHONCODE\venv\lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "d:\PYTHONCODE

{'C': 0.01, 'penalty': 'l2', 'solver': 'newton-cg'}

In [ ]:
###Here you can See 
""" 
{'C': 0.01, 'penalty': 'l2', 'solver': 'newton-cg'}

This are the Most Imporatant Features which are selected by the Grid After doing the Hyperparamter Tunning 
This Featurse Are selected by the Grid 
"""

" \n{'C': 0.01, 'penalty': 'l2', 'solver': 'newton-cg'}\n\nThis are the Most Imporatant Features which are selected by the Grid After doing the Hyperparamter Tunning \n"

In [ ]:
grid.best_score_
### This is the Best Accuarcy We got Till now 87% 

np.float64(0.8773333333333333)

In [22]:
print(grid)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')


In [24]:
Y_pred=grid.predict(X_test)
Y_pred

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0])

### RANDOMESIZED CV


In [ ]:
 # In Randomized CV , It wil Take the Randome Parameters and It will give you the Best Model 