In [1]:
import numpy as np

In [13]:
# Basic indexing in 1-D Array 

import numpy as np

# Creating a 1-D array
arr = np.array([10, 20, 30, 40, 50])

# Accessing elements
print("Element at index 0:", arr[0])  # 10
print("Element at index 3:", arr[1])  

arr[2]=50

print("Element at index 2:", arr[2])    
arr[3]=52
print("Element at index 2:", arr[3]) 
print("Element at index 4:", arr[4])  
print("Last element using negative indexing:", arr[-1]) 
print("Last element using negative indexing:", arr[-2]) 
arr[-4]=56
print("Last element using negative indexing:", arr[-4]) 
arr[-3]=99
print("Last element using negative indexing:", arr[-3]) 

## IN NUMPY ARRAY YOU CAN CHANGE THE ELEMENT AT PARTICULAR INDEX 
"""
    1) YOU CAN CHNAGE THE ELELEMNT AT ANY INDEX
    2) YOU CANNOT ADD THE ELEMENT 
    3) YOU CANNOT DELETE THE ELEMENT 
"""



Element at index 0: 10
Element at index 3: 20
Element at index 2: 50
Element at index 2: 52
Element at index 4: 50
Last element using negative indexing: 50
Last element using negative indexing: 52
Last element using negative indexing: 56
Last element using negative indexing: 99


'\n    1) YOU CAN CHNAGE THE ELELEMNT AT ANY INDEX\n    2) YOU CANNOT ADD THE ELEMENT \n    3) YOU CANNOT DELETE THE ELEMENT \n'

In [15]:
# Slicing in the 1-D array 
# Slicing syntax: arr[start:end:step]
# 'start' is inclusive, 'end' is exclusive, 'step' determines the interval.
# Slicing aso

# Example slices
print("Elements from index 1 to 3:", arr[1:4])  # [20, 30, 40]
print("Elements from start to index 2:", arr[:3])  # [10, 20, 30]
print("Elements from index 2 to end:", arr[2:])  # [30, 40, 50]
print("Every second element:", arr[::2])  # [10, 30, 50]
print("Elements in reverse order:", arr[::-1])  # [50, 40, 30, 20, 10]


Elements from index 1 to 3: [400 600 800]
Elements from start to index 2: [200 400 600]
Elements from index 2 to end: [600 800 100]
Every second element: [200 600 100]
Elements in reverse order: [100 800 600 400 200]


In [12]:
print("Elements from index 1 to 3:", arr[1:4:2])

Elements from index 1 to 3: [56 52]


In [17]:
### Understanding examples in 1-D Array 

import numpy as np

# Creating a 1-D array
arr = np.array([10, 20, 30, 40, 50])
print("Original Array:", arr)

# 1. Basic Indexing
print("\n# 1. Basic Indexing")
print("Element at index 0:", arr[0])  # First element
print("Element at index 3:", arr[3])  # Fourth element
print("Last element using negative indexing:", arr[-1])  # Last element

# 2. Slicing
print("\n# 2. Slicing")
# Slice syntax: arr[start:end:step]
print("Elements from index 1 to 3 (inclusive of 1, exclusive of 3):", arr[1:4])  # [20, 30, 40]
print(" Elelemnts from 1 to lat :-",arr[1::])
print("Elements from start to index 2:", arr[:3])  # [10, 20, 30]
print("Elements from index 2 to end:", arr[2:])  # [30, 40, 50]
print("Every second element:", arr[::2])  # [10, 30, 50]
print("Elements in reverse order:", arr[::-1])  # [50, 40, 30, 20, 10]

# 3. Conditional Indexing
print("\n# 3. Conditional Indexing")
# Access elements that meet a condition
print("Elements greater than 25:", arr[arr > 25])  # [30, 40, 50]
print("Elements divisible by 10:", arr[arr % 10 == 0])  # [10, 20, 30, 40, 50]
print("Elements divisible by 2:", arr[arr % 2 == 0]) 
print("Elements greater than 5:", arr[arr > 5])   

# 4. Fancy Indexing
print("\n# 4. Fancy Indexing")
# Select multiple elements using a list of indices
indices = [0, 2, 4]
print("Elements at indices 0, 2, and 4:", arr[indices])  # [10, 30, 50]

# 5. Modifying Elements
print("\n# 5. Modifying Elements")
arr[0] = 100  # Modify a single element
print("Array after changing the first element:", arr)  # [100, 20, 30, 40, 50]
arr[1:4] = [200, 300, 400]  # Modify a slice
arr[:4] = [200, 300, 400,500]
arr[::2] = [600, 700, 800]
print("Array after modifying elements from index start to 3:", arr)  

# 6. Combining Slicing and Conditional Indexing
print("\n# 6. Combining Slicing and Conditional Indexing")
# Access elements greater than 100 and slice the result
subset = arr[arr > 100][:2]  # Take the first two elements greater than 100
print("Subset of elements greater than 100:", subset)  # [200, 300]

# 7. Reverse Indexing and Modifications
print("\n# 7. Reverse Indexing and Modifications")
arr[::-1] = arr[::-1] * 2  # Reverse and double each element
print("Array after reversing and doubling elements:", arr)  # [100, 400, 600, 800, 200]

# Summary
print("\nFinal Array State:", arr)


Original Array: [10 20 30 40 50]

# 1. Basic Indexing
Element at index 0: 10
Element at index 3: 40
Last element using negative indexing: 50

# 2. Slicing
Elements from index 1 to 3 (inclusive of 1, exclusive of 3): [20 30 40]
 Elelemnts from 1 to lat :- [20 30 40 50]
Elements from start to index 2: [10 20 30]
Elements from index 2 to end: [30 40 50]
Every second element: [10 30 50]
Elements in reverse order: [50 40 30 20 10]

# 3. Conditional Indexing
Elements greater than 25: [30 40 50]
Elements divisible by 10: [10 20 30 40 50]
Elements divisible by 2: [10 20 30 40 50]
Elements greater than 5: [10 20 30 40 50]

# 4. Fancy Indexing
Elements at indices 0, 2, and 4: [10 30 50]

# 5. Modifying Elements
Array after changing the first element: [100  20  30  40  50]
Array after modifying elements from index start to 3: [600 300 700 500 800]

# 6. Combining Slicing and Conditional Indexing
Subset of elements greater than 100: [600 300]

# 7. Reverse Indexing and Modifications
Array after re

In [21]:
### Understanding examples in 2-D Arrays 

#**  Diffrent Ways  to Access each element in 2-D array **# 
import numpy as np

# Create a 2-D array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("Original Array:\n", arr)

# Accessing a each element mannual method 
print("Element at row 1, column 2:", arr[0, 0])
print("Element at row 1, column 2:", arr[0, 1])
print("Element at row 1, column 2:", arr[0, 2])
print("Element at row 1, column 2:", arr[0, 3])
print("Element at row 1, column 2:", arr[1, 0])
print("Element at row 1, column 2:", arr[1, 1])
print("Element at row 1, column 2:", arr[1, 2])
print("Element at row 1, column 2:", arr[1, 3])


# Accessing each element using nested loops
print("\nAccessing each element in the 2-D array:")
for i in range(arr.shape[0]):  # Iterate through rows
    for j in range(arr.shape[1]):  # Iterate through columns
        print(f"Element at row {i}, column {j}:", arr[i, j])


#### IMPORTANT :- 
"""
Explanation of arr.shape[0]:
    arr.shape[0] refers to the number of rows in the array.
    In the above example, arr.shape is (2, 3), meaning the array has:
    2 rows (first value, arr.shape[0]).
    3 columns (second value, arr.shape[1]).

Why is it useful?
1)  You can use arr.shape[0] to:
    Determine the number of rows dynamically in a program.
    Iterate through rows in a loop.

2) You can use arr.shape[1] to:
    Determine the number of cloumns dynamically in a program.
    Iterate through rows in a loop.


"""


Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element at row 1, column 2: 1
Element at row 1, column 2: 2
Element at row 1, column 2: 3
Element at row 1, column 2: 4
Element at row 1, column 2: 5
Element at row 1, column 2: 6
Element at row 1, column 2: 7
Element at row 1, column 2: 8

Accessing each element in the 2-D array:
Element at row 0, column 0: 1
Element at row 0, column 1: 2
Element at row 0, column 2: 3
Element at row 0, column 3: 4
Element at row 1, column 0: 5
Element at row 1, column 1: 6
Element at row 1, column 2: 7
Element at row 1, column 3: 8
Element at row 2, column 0: 9
Element at row 2, column 1: 10
Element at row 2, column 2: 11
Element at row 2, column 3: 12


'\nExplanation of arr.shape[0]:\n    arr.shape[0] refers to the number of rows in the array.\n    In the above example, arr.shape is (2, 3), meaning the array has:\n    2 rows (first value, arr.shape[0]).\n    3 columns (second value, arr.shape[1]).\n\nWhy is it useful?\n1)  You can use arr.shape[0] to:\n    Determine the number of rows dynamically in a program.\n    Iterate through rows in a loop.\n\n2) You can use arr.shape[1] to:\n    Determine the number of cloumns dynamically in a program.\n    Iterate through rows in a loop.\n\n\n'

In [23]:
#### #**  Diffrent Ways  to Access each row in 2-D array **# 

# Accessing a row mannaully 
print("First row:", arr[0, :])
print("Second row:", arr[1, :])
print("Third  row:", arr[2, :])



# Access each row using a loop
print("\nAccessing each row:")
for i in range(arr.shape[0]):  # Iterate through rows
    print(f"Row {i}:", arr[i])


First row: [1 2 3 4]
Second row: [5 6 7 8]
Third  row: [ 9 10 11 12]

Accessing each row:
Row 0: [1 2 3 4]
Row 1: [5 6 7 8]
Row 2: [ 9 10 11 12]


In [26]:
#### #**  Diffrent Ways  to Access each Column in 2-D array **# 
# Accessing a row mannaully 
print("First Column:", arr[:, 0])
print("Second Column:", arr[:, 1])
print("Third  Column:", arr[:, 2])
print("Fourth  Column:", arr[:, 3])




# Access each Column using a loop
print("\nAccessing each Column:")
for i in range(arr.shape[1]):  # Iterate through Column
    print(f"Row {i}:", arr[:,i])


First Column: [1 5 9]
Second Column: [ 2  6 10]
Third  Column: [ 3  7 11]
Fourth  Column: [ 4  8 12]

Accessing each Column:
Row 0: [1 5 9]
Row 1: [ 2  6 10]
Row 2: [ 3  7 11]
Row 3: [ 4  8 12]


In [27]:
# Slicing rows and columns

print("Subarray (rows 0 to 1, columns 1 to 2):\n", arr[0:2, 1:3])

Subarray (rows 0 to 1, columns 1 to 2):
 [[2 3]
 [6 7]]


In [34]:
print("Subarray (rows 0 to 2, columns 0 to 2):\n", arr[0:2, 0:2])


Subarray (rows 0 to 2, columns 0 to 2):
 [[1 2]
 [5 6]]


In [31]:
print("Subarray (rows 1 to 2, columns 1 to 2):\n", arr[1:3, 1:3])

Subarray (rows 1 to 2, columns 1 to 2):
 [[ 6  7]
 [10 11]]


In [37]:
print("Subarray (:\n", arr[1:3, 2:4])

Subarray (:
 [[ 7  8]
 [11 12]]


In [38]:
print("Subarray :\n", arr[:, 1:4])

Subarray :
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [39]:
print("Subarray :\n", arr[:, 0:3])

Subarray :
 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [41]:
print("Subarray n:-\n", arr[0:2, 0:3])

Subarray n:-
 [[1 2 3]
 [5 6 7]]


In [42]:
print("Subarray n:-\n", arr[0:2:2, 0:3:2])

Subarray n:-
 [[1 3]]


In [46]:
print("Subarray n:-\n", arr[0:3:2, 0:3:2])## Steps for cloumn and row  here.. not go to cloumn (1) directly go to cloumn 2 from cloumn 0
                                            ## not go to row (1) directly go to row 2 from row 0

Subarray n:-
 [[ 1  3]
 [ 9 11]]


In [45]:
print("Subarray n:-\n", arr[0:3, 0:3:2]) ## Steps for cloumn here.. not go to cloumn (1) directly go to cloumn 2 from cloumn 0

Subarray n:-
 [[ 1  3]
 [ 5  7]
 [ 9 11]]
