In [1]:
### DIFFRENCE BETWEEN (Python_list and NumPy ) Some practical Examples 

In [6]:
# 1) Size
# In this we are going to see the diffrence between the size to stored answer of anymultiplication between an NumpyArray and python list 
# Kon jyada size leta hai multiplication kai answer ko stored karne kai liye  
import time
import sys
import numpy as np


In [7]:
b=range(500)
print(sys.getsizeof(5)*len(b))  # Here 5 is just a randome number we taken 

# Here you can see in output is the size of the Python_list taken to stored this particular answer

14000


In [12]:
C=np.arange(500)        # As we have a see a (range) this function in Python_list like that we have (arange) this function in Numpy_array 
print(C.size*C.itemsize)

# # Here you can see in output is the size of the Numpy_array taken to stored this particular answer

4000


In [9]:
4000<14000 # The diffrence is very huge between them , so you can see that advantage to use Numpy_array

True

In [11]:
## 2) Time 
# Here we see another example wrt Time :- time taken by both to perfome the same operation 


In [24]:
a=np.array([[1,2],[3,4],[5,6]], dtype=np.float64)# # dtype:- It will convert the integer into float by using dtype
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [25]:
a.itemsize # It will rreturn the byte per character..in memory  


8

In [26]:
a=np.array([[1,2],[3,4],[5,6]], dtype=np.complex64)# # dtype:- It will convert the integer into complex number by using dtype
a


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]], dtype=complex64)

In [27]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
l=range(5)
l

range(0, 5)

In [36]:
np.arange(5) # arange it will return Numpy_array

array([0, 1, 2, 3, 4])

In [37]:
print('concatatentaion example')
print(np.char.add(['hello ','aobc'],['abc','xyz']))

concatatentaion example
['hello abc' 'aobcxyz']


In [39]:
print(np.char.multiply("hello",3))

hellohellohello


In [41]:
print(np.char.center("hello",20,fillchar='-'))

-------hello--------


In [42]:
print(np.char.capitalize("hello world"))

Hello world


In [43]:
print(np.char.lower("HELLO WORLD"))

hello world


In [47]:
print(np.char.title("How are you doing ? ")) # Convert into a good title like structure

How Are You Doing ? 


In [49]:
print(np.char.upper(['python ','data']))            # To convert a list into a captial form 
print(np.char.upper(['python ','is very easy']))

['PYTHON ' 'DATA']
['PYTHON ' 'IS VERY EASY']


In [50]:
print(np.char.split(" are you coming to the party"))

['are', 'you', 'coming', 'to', 'the', 'party']


In [51]:
print(np.char.splitlines(" are you coming \n to the party"))

[' are you coming ', ' to the party']


In [55]:
print(np.char.strip(["adarsh","anil","akash"],'a'))  # Removes the follwoing letter

['darsh' 'nil' 'kash']


In [56]:
print(np.char.join([':',"-"],['dmy','ymd']))

['d:m:y' 'y-m-d']


In [58]:
print(np.char.replace("He is a good dancer","is","was"))

He was a good dancer


In [60]:
############ ARRAY MANIPULATION ################
a=np.arange(9)
print(" The original array :")
print(a)
print()

b=a.reshape(3,3)
print(" The modified array")
print(b)

 The original array :
[0 1 2 3 4 5 6 7 8]

 The modified array
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [65]:
print(b.flatten())  ## Returns the copy of the array collapsed into the one dimension 

## It has Order:-("C","F","A") optional where C:- flattern in (row-major) , F:- Flattern in (Cloumn -major)...By-deafult is C

[0 1 2 3 4 5 6 7 8]


In [63]:
b.flatten(order='F')

array([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [67]:
a=np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [68]:
np.transpose(a)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [70]:
b=np.arange(8).reshape(2,4)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [72]:
c=b.reshape(2,2,2)
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [74]:
np.rollaxis(c,2,1) # Diagonal elements has changed

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

In [75]:
np.rollaxis(c,1) 

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])

In [76]:
np.swapaxes(c,2,1) 

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

In [2]:
## NUMPY ARITHEMATIC OPERATION
import numpy as np 

In [4]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
b=np.array([10,10,10])
b

array([10, 10, 10])

In [6]:
np.add(a,b)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [7]:
np.subtract(a,b)

array([[-10,  -9,  -8],
       [ -7,  -6,  -5],
       [ -4,  -3,  -2]])

In [9]:
np.multiply(a,b)

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [10]:
np.divide(a,b)

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8]])

In [12]:
## Slicing
a=np.arange(20)
a 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:

print(a[:4])

[0 1 2 3]


In [17]:
a[5]

np.int64(5)

In [18]:
s=slice(2,9,2)
a[s]

array([2, 4, 6, 8])

In [19]:
s=slice(2,9,3)
a[s]

array([2, 5, 8])

In [20]:
s=slice(2,12,3)
a[s]

array([ 2,  5,  8, 11])

In [21]:
## Iteration over Array 

In [23]:
a= np.arange(0,45,5)
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40])

In [25]:
a=a.reshape(3,3)
a

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [26]:
for x in np.nditer(a):
    print(x)

0
5
10
15
20
25
30
35
40


In [27]:
### Iteration Order (C-Style and f-Style)

In [29]:
print(a)
for x in np.nditer(a,order="C"):
    print(x)
for x in np.nditer(a,order='F'):
    print(x)

[[ 0  5 10]
 [15 20 25]
 [30 35 40]]
0
5
10
15
20
25
30
35
40
0
15
30
5
20
35
10
25
40


In [30]:
## Joining Arrays

In [31]:
a=np.array([[1,2],[3,4]])
print('first Array')
print(a)
b=np.array([[5,6],[7,8]])
print('Second Array')
print(b)

first Array
[[1 2]
 [3 4]]
Second Array
[[5 6]
 [7 8]]


In [33]:
print('\n')
print('Joing the two arrays along axis 0:-')
print(np.concatenate((a,b)))
print('\n')



Joing the two arrays along axis 0:-
[[1 2]
 [3 4]
 [5 6]
 [7 8]]




In [34]:
print('Joining the two arrays along axis 1:')
print(np.concatenate((a,b),axis=1))

Joining the two arrays along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [35]:
#### SPLITTING ARRAYS

In [37]:
a=np.arange(9)
print(a)
np.split(a,3)

[0 1 2 3 4 5 6 7 8]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [38]:
np.split(a,[4,5])

[array([0, 1, 2, 3]), array([4]), array([5, 6, 7, 8])]

In [40]:
np.split(a,[4,5,7])

[array([0, 1, 2, 3]), array([4]), array([5, 6]), array([7, 8])]

In [41]:
### RESIZING AN ARRAY

In [49]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape) # 
print('\n')
b=np.resize(a,(3,2))
print(b)
print(b.shape)
print('\n')
c=np.resize(a,(3,3))
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


[[1 2]
 [3 4]
 [5 6]]
(3, 2)


[[1 2 3]
 [4 5 6]
 [1 2 3]]
(3, 3)
