In [2]:
!pip install numpy

In [7]:
"""import numpy as np
arr1= np.array([1,2,3,4])
print(arr1)
print(arr1.dtype)
"""

import numpy as np

# Python list
py_list = [1, 2, 3, 4]
print(f"Python list memory: {py_list.__sizeof__()} bytes")

# NumPy array
np_array = np.array([1, 2, 3, 4])
print(f"NumPy array memory: {np_array.nbytes} bytes")

## You see the diffrence between both the storage


Python list memory: 104 bytes
NumPy array memory: 32 bytes


In [8]:
import numpy as np

# Python list
py_list = [1, "Darsh", 3.5, 4,'a']
print(f"Python list memory: {py_list.__sizeof__()} bytes")

# NumPy array
np_array = np.array([1, "Darsh", 3.5, 4,'a'])
print(f"NumPy array memory: {np_array.nbytes} bytes")

Python list memory: 104 bytes
NumPy array memory: 640 bytes


In [12]:
import numpy as np

# NumPy array
py_list = np.array([1,2,3,4,5])
print(f"Numpy array memory for Same data types memory: {np_array.nbytes} bytes")

# NumPy array
np_array = np.array([1, "Darsh", 3.5, 4,'a'])
print(f"Numpy array memory for mixed  data types memory: {np_array.nbytes} bytes")

Numpy array memory for Same data types memory: 640 bytes
Numpy array memory for mixed  data types memory: 640 bytes


In [13]:
import numpy as np

# Python list
py_list = [1, 2, 3, 4]
print(f"Python list memory same data types: {py_list.__sizeof__()} bytes")

# Pyhton List
py_list = [1, "Darsh", 3.5, 4,'a']
print(f"Python list memory mixed data types  {py_list.__sizeof__()} bytes")


Python list memory same data types: 104 bytes
Python list memory mixed data types  104 bytes


In [15]:
"""
6. Built-in Functions:
NumPy Array: Provides a rich set of mathematical and statistical functions such as np.mean(), np.median(), np.std(), etc.,
 directly on arrays, making complex operations simple.

Python List: Lacks built-in mathematical functions. You need to import modules 
like math or statistics to perform similar operations on lists.

"""

np_array = np.array([1, 2, 3, 4])
mean = np.mean(np_array)  # Built-in function

py_list = [1, 2, 3, 4]
mean = sum(py_list) / len(py_list)  # Manual calculation


## like this many more there 


In [16]:
"""
 EXPAIN "Refrence pointing method" :

 Reference Pointer Method in Python:
In Python, all variables refer to objects in memory by reference. When you assign one variable to another, you're simply creating a reference (or pointer) to the same object in memory. This behavior is distinct from copying data directly, and it applies to most mutable objects like lists, dictionaries, and NumPy arrays.

How Reference Works:
When you assign one variable to another, Python doesn't create a new copy of the object;
 instead, it just points to the original object.
Any changes made to the object via one variable will be reflected in all other variables that
 reference the same object.

"""

# Example of reference behavior in Python
a = [1, 2, 3]  # 'a' is a reference to the list [1, 2, 3]
b = a  # 'b' now references the same list as 'a'

b.append(4)  # Modify the list via 'b'

print(a)  # Output: [1, 2, 3, 4]
print(b)  # Output: [1, 2, 3, 4]



[1, 2, 3, 4]
[1, 2, 3, 4]


In [17]:
"""
3. Automatic Type Upcasting
Rule: If array elements have different types, NumPy upcasts them to a common, more general type.
Reason: Ensures that the array remains homogeneous
"""
arr = np.array([1, 2.5, "Hello"])  # Mixed types
print(arr)  # Output: ['1' '2.5' 'Hello']
print(arr.dtype)  # Output: <U5 (Unicode string)>


['1' '2.5' 'Hello']
<U32


In [18]:
"""
4. Fixed Size
Rule: A NumPy array's size is fixed at the time of creation.
Reason: Enhances computational efficiency by allocating memory only once.

"""
arr = np.array([1, 2, 3])
arr[0] = 10  # Allowed (modifying value)
# arr.append(4)  # Not allowed, raises AttributeError


In [20]:
"""
5. Broadcasting Rules
Rule: Arrays of different shapes can operate together if their shapes are compatible.
Reason: Simplifies mathematical operations without needing explicit loops.
"""
a = np.array([1, 2, 3])
b = 2
print(a + b)  # Output: [3 4 5] (scalar b is broadcast)
print(a - b)  
print(a * b) 
print(a / b)   


[3 4 5]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]


In [47]:
a = np.array([[1, 2, 3],[1,25,65],[15,25,96]])
b = 2
print(a + b)  # Output: [3 4 5] (scalar b is broadcast)
print(a - b)  
print(a * b) 
print(a / b)   

[[ 3  4  5]
 [ 3 27 67]
 [17 27 98]]
[[-1  0  1]
 [-1 23 63]
 [13 23 94]]
[[  2   4   6]
 [  2  50 130]
 [ 30  50 192]]
[[ 0.5  1.   1.5]
 [ 0.5 12.5 32.5]
 [ 7.5 12.5 48. ]]


In [22]:
"""
6. Zero-Based Indexing
Rule: NumPy arrays use zero-based indexing, like Python lists.
Reason: Consistency with Python’s standard indexing.
"""

arr = np.array([10, 20, 30])
print(arr[0])  # Output: 10


10


In [23]:
"""
7. Slicing Returns Views, Not Copies
Rule: Slicing an array returns a view (not a copy) of the original array.
Reason: Saves memory and speeds up operations.

"""
arr = np.array([1, 2, 3])
sliced = arr[0:2]
sliced[0] = 10
print(arr)  # Output: [10  2  3] (original array modified)



[10  2  3]


In [27]:
arr = np.array([1, 2, 3])
sliced = arr[0:2]
sliced[0] = 10
print(arr)  # Output: [10  2  3] (original array modified)
print(sliced)   # This is the slced array


[10  2  3]
[10  2]


In [28]:
"""
8. Immutable Shape
Rule: The shape of a NumPy array cannot be changed after creation without creating a new array.
Reason: Maintains memory structure integrity.

"""
arr = np.array([1, 2, 3, 4])
reshaped = arr.reshape(2, 2)  # Creates a new array with the desired shape
print(reshaped)


[[1 2]
 [3 4]]


In [ ]:
"""
9. Element-Wise Operations
Rule: Arithmetic operations on NumPy arrays are performed element-wise.
Reason: Supports efficient mathematical computations.

"""
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # Output: [5 7 9]
print(a - b) 
print(a * b) 
print(a / b) 


In [33]:
a = np.array([1, 2, 'a',"Adarsg",2.5,50.5,45])
b = np.array(['a', 5, 6,"Anil",205,'afsv',2.5])
print(a + b)

## If Numpy_array is of Mixed data type then it will convert into Strings and do the operation in Strings 


['1a' '25' 'a6' 'AdarsgAnil' '2.5205' '50.5afsv' '452.5']


In [35]:
a = np.array([[1, 2, 3,15],[2,45,85,20]])
b = np.array([[4, 5, 6,14],[14,85,98,74]])
print(a + b)  # Output: [5 7 9]
print(a - b) 
print(a * b) 
print(a / b) 

[[  5   7   9  29]
 [ 16 130 183  94]]
[[ -3  -3  -3   1]
 [-12 -40 -13 -54]]
[[   4   10   18  210]
 [  28 3825 8330 1480]]
[[0.25       0.4        0.5        1.07142857]
 [0.14285714 0.52941176 0.86734694 0.27027027]]


In [36]:
"""
10. Data Type Casting
Rule: During operations, NumPy casts data to the most general type in the operation.
Reason: Prevents loss of precision.

"""
arr = np.array([1, 2, 3])
result = arr + 0.5
print(result)  # Output: [1.5 2.5 3.5] (int to float)


[1.5 2.5 3.5]


In [37]:
"""11. Memory Contiguity
Rule: NumPy arrays are stored in contiguous memory blocks.
Reason: Allows for faster access and computation compared to Python lists
"""
arr = np.array([1, 2, 3])
print(arr.strides)  # Output: (8,) (bytes per step)

# While storing in continuos memory location each step take 8 bytes 


(8,)


In [ ]:
"""13. Indexing with Boolean Arrays
Rule: Boolean arrays can be used to filter elements from another array.
Reason: Provides a concise way to apply conditions
"""
arr = np.array([10, 20, 30, 40])
print(arr[arr > 20])  # Output: [30 40]


In [38]:
a = np.array([[1, 2, 3,15],[2,45,85,20]])
b = np.array([[4, 5, 6,14],[14,85,98,74]])

print(a[a>2])
print(b[a>5])
print(a[a>5])

[ 3 15 45 85 20]
[14 85 98 74]
[15 45 85 20]


In [41]:
"""
14. Structured Arrays
Rule: NumPy allows creating arrays with named fields (like a table structure).
Reason: Useful for handling structured data
"""
data = np.array([(1, 'Alice'), (2, 'Bob')], dtype=[('id', 'i4'), ('name', 'U10')])
print(data['name'])  # Output: ['Alice' 'Bob']
print(data)


['Alice' 'Bob']
[(1, 'Alice') (2, 'Bob')]


In [43]:
"""Some opratios Based on 2-D array """
import numpy as np

# Creating a 2-D array (3 rows, 4 columns)
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 1. Row and Column Structure
print("2-D Array:")
print(arr)

# 2. Indexing - Accessing elements using row and column indices
print("\nElement at row 1, column 2:", arr[1][2])  # Access element at row 1, column 2 (value 7)

# 3. Homogeneous Data - Ensure all elements are of the same type
print("\nData type of elements:", arr.dtype)

# 4. Memory Storage - Showing the shape and size of the array
print("\nShape of the array (rows, columns):", arr.shape)
print("\nShape of the array (rows, columns):", arr.reshape(4,3))
print("Size of the array (total number of elements):", arr.size)

# 5. Fixed Size - Trying to change the size of the array (this will throw an error)
try:
    arr.resize((4, 4))  # Resize to a 4x4 array
    print("\nResized 2-D Array:")
    print(arr)
except Exception as e:
    print("\nError while resizing:", e)


2-D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Element at row 1, column 2: 7

Data type of elements: int64

Shape of the array (rows, columns): (3, 4)

Shape of the array (rows, columns): [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Size of the array (total number of elements): 12

Resized 2-D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 0  0  0  0]]


In [45]:
## SOME OPARATION BASED ON 3-D array 
import numpy as np

# Creating a 3-D array (2 blocks, 3 rows, 4 columns)
arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])

# 1. Multi-dimensional Structure
print("3-D Array:")
print(arr)

# 2. Indexing - Accessing elements using depth, row, and column indices
print("\nElement at depth 1, row 2, column 3:", arr[1][2][3])  # Access element at depth 1, row 2, column 3 (value 24)

# 3. Homogeneous Data - Ensure all elements are of the same type
print("\nData type of elements:", arr.dtype)

# 4. Memory Storage - Showing the shape and size of the array
print("\nShape of the array (depth, rows, columns):", arr.shape)
print("Size of the array (total number of elements):", arr.size)

# 5. Fixed Size - Trying to change the size of the array (this will throw an error)
try:
    arr.resize((3, 3, 4))  # Resize to a new 3-D array with different dimensions
    print("\nResized 3-D Array:")
    print(arr)
except Exception as e:
    print("\nError while resizing:", e)


3-D Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Element at depth 1, row 2, column 3: 24

Data type of elements: int64

Shape of the array (depth, rows, columns): (2, 3, 4)
Size of the array (total number of elements): 24

Resized 3-D Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]]


In [46]:
# SOME OPERATIONS WRT NUMPY_ARRAYS 
import numpy as np

# 1. Creation of Arrays
# Creating a 1-D array
arr1 = np.array([1, 2, 3, 4])
# Creating a 2-D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
# Creating arrays with zeros, ones, and uninitialized values
zeros_array = np.zeros((3, 3))  # 3x3 array of zeros
ones_array = np.ones((2, 2))   # 2x2 array of ones
empty_array = np.empty((2, 3))  # 2x3 uninitialized array

# 2. Shape and Size
print("Shape of arr2:", arr2.shape)  # Dimensions of the array
print("Total elements in arr1:", arr1.size)  # Total number of elements

# 3. Reshaping
reshaped = arr1.reshape(2, 2)  # Reshaping 1-D array into 2x2
print("Reshaped array:\n", reshaped)

# 4. Indexing and Slicing
print("Element at (0, 2) in arr2:", arr2[0, 2])  # Accessing specific element
print("Slicing rows 0-1 and all columns:\n", arr2[0:2, :])  # Slicing

# 5. Statistical Functions
print("Mean of arr2:", arr2.mean())  # Mean of all elements
print("Sum of arr2:", arr2.sum())   # Sum of all elements
print("Standard deviation of arr2:", arr2.std())  # Standard deviation

# 6. Mathematical Operations
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])
dot_product = np.dot(arr3, arr4)  # Matrix multiplication
print("Dot product of arr3 and arr4:\n", dot_product)

# 7. Broadcasting
broadcasted = arr3 + 10  # Adds 10 to all elements
print("Broadcasted array:\n", broadcasted)

# 8. Logical Operations
arr5 = np.array([10, 15, 20, 25])
condition = arr5 > 15  # Element-wise condition
print("Elements greater than 15:", np.where(condition, arr5, 0))  # Conditional selection

# 9. Sorting and Searching
unsorted = np.array([3, 1, 2, 5, 4])
sorted_array = np.sort(unsorted)  # Sorting
print("Sorted array:", sorted_array)
indices = np.argsort(unsorted)  # Indices of sorted elements
print("Indices of sorted elements:", indices)

# 10. Unique Values
unique_values = np.unique(arr5)
print("Unique values in arr5:", unique_values)

# 11. Concatenation and Splitting
arr6 = np.array([[1, 2], [3, 4]])
arr7 = np.array([[5, 6], [7, 8]])
concatenated = np.concatenate((arr6, arr7), axis=0)  # Concatenating along rows
print("Concatenated array:\n", concatenated)
split = np.split(arr5, 2)  # Splitting into 2 parts
print("Split arrays:", split)

# 12. Linear Algebra
matrix = np.array([[1, 2], [3, 4]])
determinant = np.linalg.det(matrix)  # Determinant of a matrix
print("Determinant of matrix:", determinant)
eigenvalues, eigenvectors = np.linalg.eig(matrix)  # Eigenvalues and eigenvectors
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

# 13. Random Sampling
random_floats = np.random.rand(3, 3)  # Random floats
random_integers = np.random.randint(1, 10, (2, 3))  # Random integers
print("Random floats:\n", random_floats)
print("Random integers:\n", random_integers)

# 14. Data Type Conversion
float_array = arr5.astype(float)  # Convert to float
print("Float array:", float_array)

# 15. Memory Optimization
print("Memory consumed by arr6 (in bytes):", arr6.nbytes)


Shape of arr2: (2, 3)
Total elements in arr1: 4
Reshaped array:
 [[1 2]
 [3 4]]
Element at (0, 2) in arr2: 3
Slicing rows 0-1 and all columns:
 [[1 2 3]
 [4 5 6]]
Mean of arr2: 3.5
Sum of arr2: 21
Standard deviation of arr2: 1.707825127659933
Dot product of arr3 and arr4:
 [[19 22]
 [43 50]]
Broadcasted array:
 [[11 12]
 [13 14]]
Elements greater than 15: [ 0  0 20 25]
Sorted array: [1 2 3 4 5]
Indices of sorted elements: [1 2 0 4 3]
Unique values in arr5: [10 15 20 25]
Concatenated array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Split arrays: [array([10, 15]), array([20, 25])]
Determinant of matrix: -2.0000000000000004
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Random floats:
 [[0.74214099 0.0750001  0.62359179]
 [0.1907922  0.91398808 0.83601004]
 [0.29629531 0.20823493 0.58285408]]
Random integers:
 [[7 6 2]
 [3 4 4]]
Float array: [10. 15. 20. 25.]
Memory consumed by arr6 (in bytes): 32
